version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   UPGRADE_PACKAGES: "true"
      #   USE_MOBY: "false"
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=password
      - NO_VNC_PORT=6901
    shm_size: "512m"
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      # - ..:/workspace:cached
      - ..:/workspace:cached
      - app1:/home:cached
volumes:
  app1: null
  # app2: null
  # app3: null
  # app4: null
  app: 
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
